### PR TITLE
Fix Image error - delete leftovers from the previous steps of pipeline.

### PR DESCRIPTION
**Pull request by HanzJas**

### CODE REVIEW

**Comment by ashu-011** [comment]
Looks good to me !!

**Review by ashu-011 — APPROVED** [review]
LGTM !!

**Comment by deshipu** [comment]
I'm not sure if an image name is allowed to have the \t character in it, but in practice the images we will be dealing will not, so I think this is good enough for us.

**Comment by HanzJas** [comment]
Very good point Radomir! Thank you!!!
I tried it and it is possible to have \t (also the space, \n, etc) in the image name. Then I have one question for you. Is it possible to have \t in "ID" of image? I guess not. In that case I will just change "image name" with "image ID" it should work. I will try it.

**Pull request merged**
